/**
 * Curated Slack shortcode → glyph map for reactions. Hand-rolled (no emoji-mart/unicode-emoji-json
 * dependency) so this stays a static, offline dataset like the rest of the app's UI data.
 * Covers Slack's own most common reaction shortcodes plus the standard gemoji short names for
 * everything else — anything not listed here still falls back to literal `:name:` text via
 * emojiGlyph(), same as before (e.g. custom workspace emoji, which this app can't resolve).
 */
export interface EmojiEntry {
  name: string;
  glyph: string;
  keywords: string[];
}

export const EMOJI_LIST: EmojiEntry[] = [
  // Smileys & reactions
  { name: "grinning", glyph: "😀", keywords: ["happy", "smile"] },
  { name: "smiley", glyph: "😃", keywords: ["happy", "smile"] },
  { name: "smile", glyph: "😄", keywords: ["happy", "grin"] },
  { name: "grin", glyph: "😁", keywords: ["happy"] },
  { name: "laughing", glyph: "😆", keywords: ["haha", "lol"] },
  { name: "joy", glyph: "😂", keywords: ["lol", "laugh", "crying"] },
  { name: "rofl", glyph: "🤣", keywords: ["lol", "rolling"] },
  { name: "relaxed", glyph: "☺️", keywords: ["calm"] },
  { name: "blush", glyph: "😊", keywords: ["happy", "shy"] },
  { name: "innocent", glyph: "😇", keywords: ["angel"] },
  { name: "slightly_smiling_face", glyph: "🙂", keywords: ["smile"] },
  { name: "upside_down_face", glyph: "🙃", keywords: ["silly"] },
  { name: "wink", glyph: "😉", keywords: ["flirt"] },
  { name: "yum", glyph: "😋", keywords: ["tasty", "delicious"] },
  { name: "stuck_out_tongue", glyph: "😛", keywords: ["silly"] },
  { name: "heart_eyes", glyph: "😍", keywords: ["love", "crush"] },
  { name: "kissing_heart", glyph: "😘", keywords: ["kiss", "love"] },
  { name: "star_struck", glyph: "🤩", keywords: ["wow", "amazed"] },
  { name: "thinking_face", glyph: "🤔", keywords: ["hmm", "think"] },
  { name: "zipper_mouth_face", glyph: "🤐", keywords: ["quiet", "secret"] },
  { name: "raised_eyebrow", glyph: "🤨", keywords: ["skeptical", "suspicious"] },
  { name: "neutral_face", glyph: "😐", keywords: ["meh"] },
  { name: "expressionless", glyph: "😑", keywords: ["blank"] },
  { name: "no_mouth", glyph: "😶", keywords: ["silent"] },
  { name: "smirk", glyph: "😏", keywords: ["smug"] },
  { name: "unamused", glyph: "😒", keywords: ["annoyed", "meh"] },
  { name: "roll_eyes", glyph: "🙄", keywords: ["annoyed", "whatever"] },
  { name: "grimacing", glyph: "😬", keywords: ["awkward", "yikes"] },
  { name: "relieved", glyph: "😌", keywords: ["phew"] },
  { name: "pensive", glyph: "😔", keywords: ["sad"] },
  { name: "sleepy", glyph: "😪", keywords: ["tired"] },
  { name: "sleeping", glyph: "😴", keywords: ["zzz", "tired"] },
  { name: "mask", glyph: "😷", keywords: ["sick"] },
  { name: "dizzy_face", glyph: "😵", keywords: ["confused"] },
  { name: "cold_sweat", glyph: "😰", keywords: ["nervous", "anxious"] },
  { name: "sweat", glyph: "😓", keywords: ["tired", "hot"] },
  { name: "scream", glyph: "😱", keywords: ["shocked", "yikes"] },
  { name: "fearful", glyph: "😨", keywords: ["scared"] },
  { name: "cry", glyph: "😢", keywords: ["sad", "tears"] },
  { name: "sob", glyph: "😭", keywords: ["sad", "crying"] },
  { name: "angry", glyph: "😠", keywords: ["mad"] },
  { name: "rage", glyph: "😡", keywords: ["furious", "mad"] },
  { name: "triumph", glyph: "😤", keywords: ["proud", "smug"] },
  { name: "confounded", glyph: "😖", keywords: ["frustrated"] },
  { name: "persevere", glyph: "😣", keywords: ["struggling"] },
  { name: "worried", glyph: "😟", keywords: ["concerned"] },
  { name: "frowning", glyph: "😦", keywords: ["sad"] },
  { name: "slightly_frowning_face", glyph: "🙁", keywords: ["sad"] },
  { name: "flushed", glyph: "😳", keywords: ["embarrassed", "blush"] },
  { name: "hot_face", glyph: "🥵", keywords: ["hot", "sweating"] },
  { name: "cold_face", glyph: "🥶", keywords: ["cold", "freezing"] },
  { name: "nauseated_face", glyph: "🤢", keywords: ["sick", "gross"] },
  { name: "exploding_head", glyph: "🤯", keywords: ["mind blown", "shocked"] },
  { name: "partying_face", glyph: "🥳", keywords: ["celebrate", "party"] },
  { name: "shushing_face", glyph: "🤫", keywords: ["quiet", "shh"] },
  { name: "zany_face", glyph: "🤪", keywords: ["crazy", "silly"] },
  { name: "smiling_face_with_tear", glyph: "🥲", keywords: ["bittersweet"] },
  { name: "melting_face", glyph: "🫠", keywords: ["awkward", "hot"] },
  { name: "skull", glyph: "💀", keywords: ["dead", "dying"] },
  { name: "skull_and_crossbones", glyph: "☠️", keywords: ["danger"] },
  { name: "poop", glyph: "💩", keywords: ["crap", "shit"] },
  { name: "clown_face", glyph: "🤡", keywords: ["joke"] },
  { name: "japanese_ogre", glyph: "👹", keywords: ["monster"] },
  { name: "ghost", glyph: "👻", keywords: ["spooky"] },
  { name: "alien", glyph: "👽", keywords: ["ufo"] },
  { name: "robot", glyph: "🤖", keywords: ["bot", "ai"] },

  // Gestures & people
  { name: "+1", glyph: "👍", keywords: ["thumbsup", "yes", "approve", "like"] },
  { name: "-1", glyph: "👎", keywords: ["thumbsdown", "no", "disapprove", "dislike"] },
  { name: "ok_hand", glyph: "👌", keywords: ["okay", "perfect"] },
  { name: "pinching_hand", glyph: "🤏", keywords: ["small", "tiny"] },
  { name: "v", glyph: "✌️", keywords: ["peace", "victory"] },
  { name: "crossed_fingers", glyph: "🤞", keywords: ["hope", "luck"] },
  { name: "love_you_gesture", glyph: "🤟", keywords: ["love"] },
  { name: "the_horns", glyph: "🤘", keywords: ["rock"] },
  { name: "call_me_hand", glyph: "🤙", keywords: ["call"] },
  { name: "point_left", glyph: "👈", keywords: ["direction"] },
  { name: "point_right", glyph: "👉", keywords: ["direction"] },
  { name: "point_up_2", glyph: "👆", keywords: ["direction"] },
  { name: "point_down", glyph: "👇", keywords: ["direction"] },
  { name: "fu", glyph: "🖕", keywords: ["middle finger"] },
  { name: "wave", glyph: "👋", keywords: ["hello", "bye", "hi"] },
  { name: "raised_hand", glyph: "✋", keywords: ["stop", "high five"] },
  { name: "raised_hands", glyph: "🙌", keywords: ["celebrate", "praise"] },
  { name: "open_hands", glyph: "👐", keywords: ["hug"] },
  { name: "clap", glyph: "👏", keywords: ["applause", "bravo", "nice"] },
  { name: "handshake", glyph: "🤝", keywords: ["deal", "agree"] },
  { name: "pray", glyph: "🙏", keywords: ["please", "thanks", "hope"] },
  { name: "muscle", glyph: "💪", keywords: ["strong", "flex", "gym"] },
  { name: "eyes", glyph: "👀", keywords: ["look", "watching", "see"] },
  { name: "brain", glyph: "🧠", keywords: ["smart", "idea"] },
  { name: "tongue", glyph: "👅", keywords: [] },
  { name: "nose", glyph: "👃", keywords: [] },
  { name: "ear", glyph: "👂", keywords: ["listen"] },
  { name: "shrug", glyph: "🤷", keywords: ["idk", "dunno"] },
  { name: "facepalm", glyph: "🤦", keywords: ["oops", "smh"] },
  { name: "raising_hand", glyph: "🙋", keywords: ["question"] },
  { name: "bow", glyph: "🙇", keywords: ["sorry", "respect"] },

  // Hearts & celebration
  { name: "heart", glyph: "❤️", keywords: ["love"] },
  { name: "orange_heart", glyph: "🧡", keywords: ["love"] },
  { name: "yellow_heart", glyph: "💛", keywords: ["love"] },
  { name: "green_heart", glyph: "💚", keywords: ["love"] },
  { name: "blue_heart", glyph: "💙", keywords: ["love"] },
  { name: "purple_heart", glyph: "💜", keywords: ["love"] },
  { name: "black_heart", glyph: "🖤", keywords: ["love"] },
  { name: "white_heart", glyph: "🤍", keywords: ["love"] },
  { name: "broken_heart", glyph: "💔", keywords: ["sad", "heartbreak"] },
  { name: "two_hearts", glyph: "💕", keywords: ["love"] },
  { name: "sparkling_heart", glyph: "💖", keywords: ["love"] },
  { name: "heart_eyes_cat", glyph: "😻", keywords: ["love", "cat"] },
  { name: "tada", glyph: "🎉", keywords: ["party", "celebrate", "congrats"] },
  { name: "confetti_ball", glyph: "🎊", keywords: ["party", "celebrate"] },
  { name: "sparkles", glyph: "✨", keywords: ["shiny", "new"] },
  { name: "star", glyph: "⭐", keywords: ["favorite"] },
  { name: "star2", glyph: "🌟", keywords: ["favorite", "shiny"] },
  { name: "fire", glyph: "🔥", keywords: ["hot", "lit", "great"] },
  { name: "100", glyph: "💯", keywords: ["perfect", "score"] },
  { name: "boom", glyph: "💥", keywords: ["explosion", "wow"] },
  { name: "zap", glyph: "⚡", keywords: ["fast", "power"] },
  { name: "gift", glyph: "🎁", keywords: ["present"] },
  { name: "birthday", glyph: "🎂", keywords: ["cake", "party"] },
  { name: "balloon", glyph: "🎈", keywords: ["party"] },
  { name: "trophy", glyph: "🏆", keywords: ["win", "winner"] },
  { name: "medal", glyph: "🏅", keywords: ["win", "award"] },
  { name: "rainbow", glyph: "🌈", keywords: ["pride", "colorful"] },

  // Status / check marks
  { name: "white_check_mark", glyph: "✅", keywords: ["done", "yes", "check"] },
  { name: "heavy_check_mark", glyph: "✔️", keywords: ["done", "check"] },
  { name: "x", glyph: "❌", keywords: ["no", "wrong", "cancel"] },
  { name: "heavy_multiplication_x", glyph: "✖️", keywords: ["no", "cancel"] },
  { name: "warning", glyph: "⚠️", keywords: ["caution", "alert"] },
  { name: "question", glyph: "❓", keywords: ["confused"] },
  { name: "exclamation", glyph: "❗", keywords: ["important"] },
  { name: "no_entry", glyph: "⛔", keywords: ["stop", "blocked"] },
  { name: "stop_sign", glyph: "🛑", keywords: ["stop"] },
  { name: "recycle", glyph: "♻️", keywords: ["reuse"] },
  { name: "lock", glyph: "🔒", keywords: ["secure", "private"] },
  { name: "unlock", glyph: "🔓", keywords: ["open"] },
  { name: "bell", glyph: "🔔", keywords: ["notification", "alert"] },
  { name: "mute", glyph: "🔇", keywords: ["silent"] },
  { name: "loudspeaker", glyph: "📢", keywords: ["announcement"] },
  { name: "hourglass", glyph: "⏳", keywords: ["waiting", "loading"] },
  { name: "alarm_clock", glyph: "⏰", keywords: ["time", "reminder"] },
  { name: "calendar", glyph: "📅", keywords: ["date", "schedule"] },
  { name: "pushpin", glyph: "📌", keywords: ["pin"] },
  { name: "round_pushpin", glyph: "📍", keywords: ["location"] },
  { name: "link", glyph: "🔗", keywords: ["url"] },
  { name: "bookmark", glyph: "🔖", keywords: ["save"] },

  // Objects & work
  { name: "rocket", glyph: "🚀", keywords: ["launch", "ship", "fast"] },
  { name: "computer", glyph: "💻", keywords: ["laptop", "code"] },
  { name: "desktop_computer", glyph: "🖥️", keywords: ["computer"] },
  { name: "keyboard", glyph: "⌨️", keywords: ["type"] },
  { name: "bug", glyph: "🐛", keywords: ["error", "issue"] },
  { name: "hammer_and_wrench", glyph: "🛠️", keywords: ["tools", "build", "fix"] },
  { name: "wrench", glyph: "🔧", keywords: ["fix", "tools"] },
  { name: "gear", glyph: "⚙️", keywords: ["settings", "config"] },
  { name: "mag", glyph: "🔍", keywords: ["search", "find"] },
  { name: "bulb", glyph: "💡", keywords: ["idea"] },
  { name: "memo", glyph: "📝", keywords: ["note", "write"] },
  { name: "clipboard", glyph: "📋", keywords: ["copy", "notes"] },
  { name: "email", glyph: "📧", keywords: ["mail", "message"] },
  { name: "inbox_tray", glyph: "📥", keywords: ["receive"] },
  { name: "outbox_tray", glyph: "📤", keywords: ["send"] },
  { name: "file_folder", glyph: "📁", keywords: ["files"] },
  { name: "page_facing_up", glyph: "📄", keywords: ["document", "file"] },
  { name: "paperclip", glyph: "📎", keywords: ["attachment"] },
  { name: "chart_with_upwards_trend", glyph: "📈", keywords: ["growth", "stats"] },
  { name: "chart_with_downwards_trend", glyph: "📉", keywords: ["decline", "stats"] },
  { name: "moneybag", glyph: "💰", keywords: ["money"] },
  { name: "credit_card", glyph: "💳", keywords: ["payment"] },
  { name: "package", glyph: "📦", keywords: ["box", "delivery"] },
  { name: "mailbox", glyph: "📬", keywords: ["mail"] },
  { name: "phone", glyph: "☎️", keywords: ["call"] },
  { name: "calling", glyph: "📲", keywords: ["call", "phone"] },
  { name: "microphone", glyph: "🎤", keywords: ["mic", "voice", "sing"] },
  { name: "headphones", glyph: "🎧", keywords: ["music", "audio"] },
  { name: "musical_note", glyph: "🎵", keywords: ["music", "song"] },
  { name: "camera", glyph: "📷", keywords: ["photo"] },
  { name: "video_camera", glyph: "🎥", keywords: ["video"] },
  { name: "tv", glyph: "📺", keywords: ["screen"] },
  { name: "battery", glyph: "🔋", keywords: ["power", "charge"] },
  { name: "electric_plug", glyph: "🔌", keywords: ["power", "charger"] },

  // Nature & misc
  { name: "sun", glyph: "☀️", keywords: ["sunny", "weather"] },
  { name: "cloud", glyph: "☁️", keywords: ["weather"] },
  { name: "umbrella", glyph: "☔", keywords: ["rain"] },
  { name: "snowflake", glyph: "❄️", keywords: ["cold", "snow"] },
  { name: "coffee", glyph: "☕", keywords: ["drink", "morning"] },
  { name: "beer", glyph: "🍺", keywords: ["drink", "cheers"] },
  { name: "beers", glyph: "🍻", keywords: ["cheers", "drinks"] },
  { name: "pizza", glyph: "🍕", keywords: ["food"] },
  { name: "hamburger", glyph: "🍔", keywords: ["food"] },
  { name: "taco", glyph: "🌮", keywords: ["food"] },
  { name: "cake", glyph: "🍰", keywords: ["dessert"] },
  { name: "doughnut", glyph: "🍩", keywords: ["dessert"] },
  { name: "cookie", glyph: "🍪", keywords: ["dessert"] },
  { name: "dog", glyph: "🐶", keywords: ["pet"] },
  { name: "cat", glyph: "🐱", keywords: ["pet"] },
  { name: "unicorn", glyph: "🦄", keywords: ["magic"] },
  { name: "monkey_face", glyph: "🐵", keywords: [] },
  { name: "see_no_evil", glyph: "🙈", keywords: ["oops"] },
  { name: "hear_no_evil", glyph: "🙉", keywords: [] },
  { name: "speak_no_evil", glyph: "🙊", keywords: ["secret"] },
  { name: "earth_americas", glyph: "🌎", keywords: ["world", "global"] },
  { name: "globe_with_meridians", glyph: "🌐", keywords: ["world", "internet"] },
  { name: "flag-checkered", glyph: "🏁", keywords: ["done", "finish"] },
  { name: "triangular_flag_on_post", glyph: "🚩", keywords: ["flag", "report"] },
];

const EMOJI_BY_NAME = new Map(EMOJI_LIST.map((e) => [e.name, e]));

export function emojiGlyph(name: string): string {
  return EMOJI_BY_NAME.get(name)?.glyph ?? `:${name}:`;
}

export function searchEmoji(query: string, limit = 48): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return EMOJI_LIST.slice(0, limit);

  const results: EmojiEntry[] = [];
  for (const entry of EMOJI_LIST) {
    if (entry.name.includes(q) || entry.keywords.some((k) => k.includes(q))) {
      results.push(entry);
      if (results.length >= limit) break;
    }
  }
  return results;
}
