/**
 * Curated Slack shortcode → glyph map for reactions. Hand-rolled (no emoji-mart/unicode-emoji-json
 * dependency) so this stays a static, offline dataset like the rest of the app's UI data.
 * Covers Slack's own most common reaction shortcodes plus the standard gemoji short names for
 * everything else — anything not listed here still falls back to literal `:name:` text via
 * emojiGlyph(), same as before (e.g. custom workspace emoji, which this app can't resolve).
 */
export interface EmojiEntry {
  name: string;
  glyph: string;
  keywords: string[];
  /** Set for a workspace's custom emoji, which are images rather than glyphs. */
  url?: string;
}

export const EMOJI_LIST: EmojiEntry[] = [
  // Smileys & reactions
  { name: "grinning", glyph: "😀", keywords: ["happy", "smile"] },
  { name: "smiley", glyph: "😃", keywords: ["happy", "smile"] },
  { name: "smile", glyph: "😄", keywords: ["happy", "grin"] },
  { name: "grin", glyph: "😁", keywords: ["happy"] },
  { name: "laughing", glyph: "😆", keywords: ["haha", "lol"] },
  { name: "joy", glyph: "😂", keywords: ["lol", "laugh", "crying"] },
  { name: "rofl", glyph: "🤣", keywords: ["lol", "rolling"] },
  { name: "relaxed", glyph: "☺️", keywords: ["calm"] },
  { name: "blush", glyph: "😊", keywords: ["happy", "shy"] },
  { name: "innocent", glyph: "😇", keywords: ["angel"] },
  { name: "slightly_smiling_face", glyph: "🙂", keywords: ["smile"] },
  { name: "upside_down_face", glyph: "🙃", keywords: ["silly"] },
  { name: "wink", glyph: "😉", keywords: ["flirt"] },
  { name: "yum", glyph: "😋", keywords: ["tasty", "delicious"] },
  { name: "stuck_out_tongue", glyph: "😛", keywords: ["silly"] },
  { name: "heart_eyes", glyph: "😍", keywords: ["love", "crush"] },
  { name: "kissing_heart", glyph: "😘", keywords: ["kiss", "love"] },
  { name: "star_struck", glyph: "🤩", keywords: ["wow", "amazed"] },
  { name: "thinking_face", glyph: "🤔", keywords: ["hmm", "think"] },
  { name: "zipper_mouth_face", glyph: "🤐", keywords: ["quiet", "secret"] },
  { name: "raised_eyebrow", glyph: "🤨", keywords: ["skeptical", "suspicious"] },
  { name: "neutral_face", glyph: "😐", keywords: ["meh"] },
  { name: "expressionless", glyph: "😑", keywords: ["blank"] },
  { name: "no_mouth", glyph: "😶", keywords: ["silent"] },
  { name: "smirk", glyph: "😏", keywords: ["smug"] },
  { name: "unamused", glyph: "😒", keywords: ["annoyed", "meh"] },
  { name: "roll_eyes", glyph: "🙄", keywords: ["annoyed", "whatever"] },
  { name: "grimacing", glyph: "😬", keywords: ["awkward", "yikes"] },
  { name: "relieved", glyph: "😌", keywords: ["phew"] },
  { name: "pensive", glyph: "😔", keywords: ["sad"] },
  { name: "sleepy", glyph: "😪", keywords: ["tired"] },
  { name: "sleeping", glyph: "😴", keywords: ["zzz", "tired"] },
  { name: "mask", glyph: "😷", keywords: ["sick"] },
  { name: "dizzy_face", glyph: "😵", keywords: ["confused"] },
  { name: "cold_sweat", glyph: "😰", keywords: ["nervous", "anxious"] },
  { name: "sweat", glyph: "😓", keywords: ["tired", "hot"] },
  { name: "scream", glyph: "😱", keywords: ["shocked", "yikes"] },
  { name: "fearful", glyph: "😨", keywords: ["scared"] },
  { name: "cry", glyph: "😢", keywords: ["sad", "tears"] },
  { name: "sob", glyph: "😭", keywords: ["sad", "crying"] },
  { name: "angry", glyph: "😠", keywords: ["mad"] },
  { name: "rage", glyph: "😡", keywords: ["furious", "mad"] },
  { name: "triumph", glyph: "😤", keywords: ["proud", "smug"] },
  { name: "confounded", glyph: "😖", keywords: ["frustrated"] },
  { name: "persevere", glyph: "😣", keywords: ["struggling"] },
  { name: "worried", glyph: "😟", keywords: ["concerned"] },
  { name: "frowning", glyph: "😦", keywords: ["sad"] },
  { name: "slightly_frowning_face", glyph: "🙁", keywords: ["sad"] },
  { name: "flushed", glyph: "😳", keywords: ["embarrassed", "blush"] },
  { name: "hot_face", glyph: "🥵", keywords: ["hot", "sweating"] },
  { name: "cold_face", glyph: "🥶", keywords: ["cold", "freezing"] },
  { name: "nauseated_face", glyph: "🤢", keywords: ["sick", "gross"] },
  { name: "exploding_head", glyph: "🤯", keywords: ["mind blown", "shocked"] },
  { name: "partying_face", glyph: "🥳", keywords: ["celebrate", "party"] },
  { name: "shushing_face", glyph: "🤫", keywords: ["quiet", "shh"] },
  { name: "zany_face", glyph: "🤪", keywords: ["crazy", "silly"] },
  { name: "smiling_face_with_tear", glyph: "🥲", keywords: ["bittersweet"] },
  { name: "melting_face", glyph: "🫠", keywords: ["awkward", "hot"] },
  { name: "skull", glyph: "💀", keywords: ["dead", "dying"] },
  { name: "skull_and_crossbones", glyph: "☠️", keywords: ["danger"] },
  { name: "poop", glyph: "💩", keywords: ["crap", "shit"] },
  { name: "clown_face", glyph: "🤡", keywords: ["joke"] },
  { name: "japanese_ogre", glyph: "👹", keywords: ["monster"] },
  { name: "ghost", glyph: "👻", keywords: ["spooky"] },
  { name: "alien", glyph: "👽", keywords: ["ufo"] },
  { name: "robot", glyph: "🤖", keywords: ["bot", "ai"] },

  // Gestures & people
  { name: "+1", glyph: "👍", keywords: ["thumbsup", "yes", "approve", "like"] },
  { name: "-1", glyph: "👎", keywords: ["thumbsdown", "no", "disapprove", "dislike"] },
  { name: "ok_hand", glyph: "👌", keywords: ["okay", "perfect"] },
  { name: "pinching_hand", glyph: "🤏", keywords: ["small", "tiny"] },
  { name: "v", glyph: "✌️", keywords: ["peace", "victory"] },
  { name: "crossed_fingers", glyph: "🤞", keywords: ["hope", "luck"] },
  { name: "love_you_gesture", glyph: "🤟", keywords: ["love"] },
  { name: "the_horns", glyph: "🤘", keywords: ["rock"] },
  { name: "call_me_hand", glyph: "🤙", keywords: ["call"] },
  { name: "point_left", glyph: "👈", keywords: ["direction"] },
  { name: "point_right", glyph: "👉", keywords: ["direction"] },
  { name: "point_up_2", glyph: "👆", keywords: ["direction"] },
  { name: "point_down", glyph: "👇", keywords: ["direction"] },
  { name: "fu", glyph: "🖕", keywords: ["middle finger"] },
  { name: "wave", glyph: "👋", keywords: ["hello", "bye", "hi"] },
  { name: "raised_hand", glyph: "✋", keywords: ["stop", "high five"] },
  { name: "raised_hands", glyph: "🙌", keywords: ["celebrate", "praise"] },
  { name: "open_hands", glyph: "👐", keywords: ["hug"] },
  { name: "clap", glyph: "👏", keywords: ["applause", "bravo", "nice"] },
  { name: "handshake", glyph: "🤝", keywords: ["deal", "agree"] },
  { name: "pray", glyph: "🙏", keywords: ["please", "thanks", "hope"] },
  { name: "muscle", glyph: "💪", keywords: ["strong", "flex", "gym"] },
  { name: "eyes", glyph: "👀", keywords: ["look", "watching", "see"] },
  { name: "brain", glyph: "🧠", keywords: ["smart", "idea"] },
  { name: "tongue", glyph: "👅", keywords: [] },
  { name: "nose", glyph: "👃", keywords: [] },
  { name: "ear", glyph: "👂", keywords: ["listen"] },
  { name: "shrug", glyph: "🤷", keywords: ["idk", "dunno"] },
  { name: "facepalm", glyph: "🤦", keywords: ["oops", "smh"] },
  { name: "raising_hand", glyph: "🙋", keywords: ["question"] },
  { name: "bow", glyph: "🙇", keywords: ["sorry", "respect"] },

  // Hearts & celebration
  { name: "heart", glyph: "❤️", keywords: ["love"] },
  { name: "orange_heart", glyph: "🧡", keywords: ["love"] },
  { name: "yellow_heart", glyph: "💛", keywords: ["love"] },
  { name: "green_heart", glyph: "💚", keywords: ["love"] },
  { name: "blue_heart", glyph: "💙", keywords: ["love"] },
  { name: "purple_heart", glyph: "💜", keywords: ["love"] },
  { name: "black_heart", glyph: "🖤", keywords: ["love"] },
  { name: "white_heart", glyph: "🤍", keywords: ["love"] },
  { name: "broken_heart", glyph: "💔", keywords: ["sad", "heartbreak"] },
  { name: "two_hearts", glyph: "💕", keywords: ["love"] },
  { name: "sparkling_heart", glyph: "💖", keywords: ["love"] },
  { name: "heart_eyes_cat", glyph: "😻", keywords: ["love", "cat"] },
  { name: "tada", glyph: "🎉", keywords: ["party", "celebrate", "congrats"] },
  { name: "confetti_ball", glyph: "🎊", keywords: ["party", "celebrate"] },
  { name: "sparkles", glyph: "✨", keywords: ["shiny", "new"] },
  { name: "star", glyph: "⭐", keywords: ["favorite"] },
  { name: "star2", glyph: "🌟", keywords: ["favorite", "shiny"] },
  { name: "fire", glyph: "🔥", keywords: ["hot", "lit", "great"] },
  { name: "100", glyph: "💯", keywords: ["perfect", "score"] },
  { name: "boom", glyph: "💥", keywords: ["explosion", "wow"] },
  { name: "zap", glyph: "⚡", keywords: ["fast", "power"] },
  { name: "gift", glyph: "🎁", keywords: ["present"] },
  { name: "birthday", glyph: "🎂", keywords: ["cake", "party"] },
  { name: "balloon", glyph: "🎈", keywords: ["party"] },
  { name: "trophy", glyph: "🏆", keywords: ["win", "winner"] },
  { name: "medal", glyph: "🏅", keywords: ["win", "award"] },
  { name: "rainbow", glyph: "🌈", keywords: ["pride", "colorful"] },

  // Status / check marks
  { name: "white_check_mark", glyph: "✅", keywords: ["done", "yes", "check"] },
  { name: "heavy_check_mark", glyph: "✔️", keywords: ["done", "check"] },
  { name: "x", glyph: "❌", keywords: ["no", "wrong", "cancel"] },
  { name: "heavy_multiplication_x", glyph: "✖️", keywords: ["no", "cancel"] },
  { name: "warning", glyph: "⚠️", keywords: ["caution", "alert"] },
  { name: "question", glyph: "❓", keywords: ["confused"] },
  { name: "exclamation", glyph: "❗", keywords: ["important"] },
  { name: "no_entry", glyph: "⛔", keywords: ["stop", "blocked"] },
  { name: "stop_sign", glyph: "🛑", keywords: ["stop"] },
  { name: "recycle", glyph: "♻️", keywords: ["reuse"] },
  { name: "lock", glyph: "🔒", keywords: ["secure", "private"] },
  { name: "unlock", glyph: "🔓", keywords: ["open"] },
  { name: "bell", glyph: "🔔", keywords: ["notification", "alert"] },
  { name: "mute", glyph: "🔇", keywords: ["silent"] },
  { name: "loudspeaker", glyph: "📢", keywords: ["announcement"] },
  { name: "hourglass", glyph: "⏳", keywords: ["waiting", "loading"] },
  { name: "alarm_clock", glyph: "⏰", keywords: ["time", "reminder"] },
  { name: "calendar", glyph: "📅", keywords: ["date", "schedule"] },
  { name: "pushpin", glyph: "📌", keywords: ["pin"] },
  { name: "round_pushpin", glyph: "📍", keywords: ["location"] },
  { name: "link", glyph: "🔗", keywords: ["url"] },
  { name: "bookmark", glyph: "🔖", keywords: ["save"] },

  // Objects & work
  { name: "rocket", glyph: "🚀", keywords: ["launch", "ship", "fast"] },
  { name: "computer", glyph: "💻", keywords: ["laptop", "code"] },
  { name: "desktop_computer", glyph: "🖥️", keywords: ["computer"] },
  { name: "keyboard", glyph: "⌨️", keywords: ["type"] },
  { name: "bug", glyph: "🐛", keywords: ["error", "issue"] },
  { name: "hammer_and_wrench", glyph: "🛠️", keywords: ["tools", "build", "fix"] },
  { name: "wrench", glyph: "🔧", keywords: ["fix", "tools"] },
  { name: "gear", glyph: "⚙️", keywords: ["settings", "config"] },
  { name: "mag", glyph: "🔍", keywords: ["search", "find"] },
  { name: "bulb", glyph: "💡", keywords: ["idea"] },
  { name: "memo", glyph: "📝", keywords: ["note", "write"] },
  { name: "clipboard", glyph: "📋", keywords: ["copy", "notes"] },
  { name: "email", glyph: "📧", keywords: ["mail", "message"] },
  { name: "inbox_tray", glyph: "📥", keywords: ["receive"] },
  { name: "outbox_tray", glyph: "📤", keywords: ["send"] },
  { name: "file_folder", glyph: "📁", keywords: ["files"] },
  { name: "page_facing_up", glyph: "📄", keywords: ["document", "file"] },
  { name: "paperclip", glyph: "📎", keywords: ["attachment"] },
  { name: "chart_with_upwards_trend", glyph: "📈", keywords: ["growth", "stats"] },
  { name: "chart_with_downwards_trend", glyph: "📉", keywords: ["decline", "stats"] },
  { name: "moneybag", glyph: "💰", keywords: ["money"] },
  { name: "credit_card", glyph: "💳", keywords: ["payment"] },
  { name: "package", glyph: "📦", keywords: ["box", "delivery"] },
  { name: "mailbox", glyph: "📬", keywords: ["mail"] },
  { name: "phone", glyph: "☎️", keywords: ["call"] },
  { name: "calling", glyph: "📲", keywords: ["call", "phone"] },
  { name: "microphone", glyph: "🎤", keywords: ["mic", "voice", "sing"] },
  { name: "headphones", glyph: "🎧", keywords: ["music", "audio"] },
  { name: "musical_note", glyph: "🎵", keywords: ["music", "song"] },
  { name: "camera", glyph: "📷", keywords: ["photo"] },
  { name: "video_camera", glyph: "🎥", keywords: ["video"] },
  { name: "tv", glyph: "📺", keywords: ["screen"] },
  { name: "battery", glyph: "🔋", keywords: ["power", "charge"] },
  { name: "electric_plug", glyph: "🔌", keywords: ["power", "charger"] },

  // Nature & misc
  { name: "sun", glyph: "☀️", keywords: ["sunny", "weather"] },
  { name: "cloud", glyph: "☁️", keywords: ["weather"] },
  { name: "umbrella", glyph: "☔", keywords: ["rain"] },
  { name: "snowflake", glyph: "❄️", keywords: ["cold", "snow"] },
  { name: "coffee", glyph: "☕", keywords: ["drink", "morning"] },
  { name: "beer", glyph: "🍺", keywords: ["drink", "cheers"] },
  { name: "beers", glyph: "🍻", keywords: ["cheers", "drinks"] },
  { name: "pizza", glyph: "🍕", keywords: ["food"] },
  { name: "hamburger", glyph: "🍔", keywords: ["food"] },
  { name: "taco", glyph: "🌮", keywords: ["food"] },
  { name: "cake", glyph: "🍰", keywords: ["dessert"] },
  { name: "doughnut", glyph: "🍩", keywords: ["dessert"] },
  { name: "cookie", glyph: "🍪", keywords: ["dessert"] },
  { name: "dog", glyph: "🐶", keywords: ["pet"] },
  { name: "cat", glyph: "🐱", keywords: ["pet"] },
  { name: "unicorn", glyph: "🦄", keywords: ["magic"] },
  { name: "monkey_face", glyph: "🐵", keywords: [] },
  { name: "see_no_evil", glyph: "🙈", keywords: ["oops"] },
  { name: "hear_no_evil", glyph: "🙉", keywords: [] },
  { name: "speak_no_evil", glyph: "🙊", keywords: ["secret"] },
  { name: "earth_americas", glyph: "🌎", keywords: ["world", "global"] },
  { name: "globe_with_meridians", glyph: "🌐", keywords: ["world", "internet"] },
  { name: "flag-checkered", glyph: "🏁", keywords: ["done", "finish"] },
  { name: "triangular_flag_on_post", glyph: "🚩", keywords: ["flag", "report"] },

  // More animals & nature
  { name: "bear", glyph: "🐻", keywords: ["animal"] },
  { name: "panda_face", glyph: "🐼", keywords: ["animal"] },
  { name: "koala", glyph: "🐨", keywords: ["animal"] },
  { name: "tiger", glyph: "🐯", keywords: ["animal"] },
  { name: "lion_face", glyph: "🦁", keywords: ["animal"] },
  { name: "fox_face", glyph: "🦊", keywords: ["animal"] },
  { name: "wolf", glyph: "🐺", keywords: ["animal"] },
  { name: "horse", glyph: "🐴", keywords: ["animal"] },
  { name: "cow", glyph: "🐮", keywords: ["animal"] },
  { name: "pig", glyph: "🐷", keywords: ["animal"] },
  { name: "rabbit", glyph: "🐰", keywords: ["animal", "bunny"] },
  { name: "chicken", glyph: "🐔", keywords: ["animal"] },
  { name: "penguin", glyph: "🐧", keywords: ["animal"] },
  { name: "frog", glyph: "🐸", keywords: ["animal"] },
  { name: "turtle", glyph: "🐢", keywords: ["animal", "slow"] },
  { name: "snake", glyph: "🐍", keywords: ["animal"] },
  { name: "octopus", glyph: "🐙", keywords: ["animal"] },
  { name: "whale", glyph: "🐳", keywords: ["animal"] },
  { name: "dolphin", glyph: "🐬", keywords: ["animal"] },
  { name: "shark", glyph: "🦈", keywords: ["animal"] },
  { name: "butterfly", glyph: "🦋", keywords: ["animal"] },
  { name: "bee", glyph: "🐝", keywords: ["animal", "bug"] },
  { name: "spider", glyph: "🕷️", keywords: ["animal", "creepy"] },
  { name: "tree", glyph: "🌳", keywords: ["nature"] },
  { name: "palm_tree", glyph: "🌴", keywords: ["tropical", "vacation"] },
  { name: "cactus", glyph: "🌵", keywords: ["nature"] },
  { name: "seedling", glyph: "🌱", keywords: ["growth", "new"] },
  { name: "four_leaf_clover", glyph: "🍀", keywords: ["luck"] },
  { name: "maple_leaf", glyph: "🍁", keywords: ["autumn", "fall"] },
  { name: "sunflower", glyph: "🌻", keywords: ["flower"] },
  { name: "tulip", glyph: "🌷", keywords: ["flower"] },
  { name: "cherry_blossom", glyph: "🌸", keywords: ["flower", "spring"] },
  { name: "rose", glyph: "🌹", keywords: ["flower", "love"] },
  { name: "full_moon", glyph: "🌕", keywords: ["night"] },
  { name: "crescent_moon", glyph: "🌙", keywords: ["night"] },
  { name: "comet", glyph: "☄️", keywords: ["space"] },
  { name: "milky_way", glyph: "🌌", keywords: ["space", "stars"] },
  { name: "ocean", glyph: "🌊", keywords: ["wave", "sea"] },
  { name: "volcano", glyph: "🌋", keywords: ["nature"] },
  { name: "mountain", glyph: "⛰️", keywords: ["nature"] },

  // More food & drink
  { name: "apple", glyph: "🍎", keywords: ["fruit"] },
  { name: "banana", glyph: "🍌", keywords: ["fruit"] },
  { name: "grapes", glyph: "🍇", keywords: ["fruit"] },
  { name: "strawberry", glyph: "🍓", keywords: ["fruit"] },
  { name: "watermelon", glyph: "🍉", keywords: ["fruit"] },
  { name: "lemon", glyph: "🍋", keywords: ["fruit"] },
  { name: "avocado", glyph: "🥑", keywords: ["food"] },
  { name: "carrot", glyph: "🥕", keywords: ["food"] },
  { name: "corn", glyph: "🌽", keywords: ["food"] },
  { name: "bread", glyph: "🍞", keywords: ["food"] },
  { name: "cheese", glyph: "🧀", keywords: ["food"] },
  { name: "bacon", glyph: "🥓", keywords: ["food"] },
  { name: "fried_shrimp", glyph: "🍤", keywords: ["food"] },
  { name: "sushi", glyph: "🍣", keywords: ["food"] },
  { name: "ramen", glyph: "🍜", keywords: ["food", "noodles"] },
  { name: "spaghetti", glyph: "🍝", keywords: ["food", "pasta"] },
  { name: "curry", glyph: "🍛", keywords: ["food"] },
  { name: "popcorn", glyph: "🍿", keywords: ["snack", "movie"] },
  { name: "ice_cream", glyph: "🍨", keywords: ["dessert"] },
  { name: "chocolate_bar", glyph: "🍫", keywords: ["dessert", "candy"] },
  { name: "candy", glyph: "🍬", keywords: ["sweet"] },
  { name: "honey_pot", glyph: "🍯", keywords: ["sweet"] },
  { name: "wine_glass", glyph: "🍷", keywords: ["drink", "alcohol"] },
  { name: "cocktail", glyph: "🍸", keywords: ["drink", "alcohol"] },
  { name: "tropical_drink", glyph: "🍹", keywords: ["drink", "vacation"] },
  { name: "champagne", glyph: "🍾", keywords: ["celebrate", "drink"] },
  { name: "tea", glyph: "🍵", keywords: ["drink"] },
  { name: "baby_bottle", glyph: "🍼", keywords: ["baby"] },

  // Activities, sports & travel
  { name: "soccer", glyph: "⚽", keywords: ["sports", "football"] },
  { name: "basketball", glyph: "🏀", keywords: ["sports"] },
  { name: "football", glyph: "🏈", keywords: ["sports", "american"] },
  { name: "baseball", glyph: "⚾", keywords: ["sports"] },
  { name: "tennis", glyph: "🎾", keywords: ["sports"] },
  { name: "volleyball", glyph: "🏐", keywords: ["sports"] },
  { name: "rugby_football", glyph: "🏉", keywords: ["sports"] },
  { name: "8ball", glyph: "🎱", keywords: ["pool", "billiards"] },
  { name: "golf", glyph: "⛳", keywords: ["sports"] },
  { name: "bow_and_arrow", glyph: "🏹", keywords: ["archery"] },
  { name: "fishing_pole_and_fish", glyph: "🎣", keywords: ["fishing"] },
  { name: "running", glyph: "🏃", keywords: ["run", "exercise"] },
  { name: "swimmer", glyph: "🏊", keywords: ["swim", "exercise"] },
  { name: "weight_lifting", glyph: "🏋️", keywords: ["gym", "exercise"] },
  { name: "bicyclist", glyph: "🚴", keywords: ["cycling"] },
  { name: "first_place_medal", glyph: "🥇", keywords: ["win", "gold", "first"] },
  { name: "chess_pawn", glyph: "♟️", keywords: ["game", "strategy"] },
  { name: "video_game", glyph: "🎮", keywords: ["gaming"] },
  { name: "dart", glyph: "🎯", keywords: ["target", "goal"] },
  { name: "ticket", glyph: "🎫", keywords: ["event"] },
  { name: "circus_tent", glyph: "🎪", keywords: ["event"] },
  { name: "art", glyph: "🎨", keywords: ["paint", "creative"] },
  { name: "guitar", glyph: "🎸", keywords: ["music"] },
  { name: "trumpet", glyph: "🎺", keywords: ["music"] },
  { name: "airplane", glyph: "✈️", keywords: ["travel", "flight"] },
  { name: "car", glyph: "🚗", keywords: ["travel", "drive"] },
  { name: "taxi", glyph: "🚕", keywords: ["travel"] },
  { name: "bus", glyph: "🚌", keywords: ["travel"] },
  { name: "train", glyph: "🚆", keywords: ["travel"] },
  { name: "ship", glyph: "🚢", keywords: ["travel", "boat"] },
  { name: "anchor", glyph: "⚓", keywords: ["boat", "sea"] },
  { name: "motorcycle", glyph: "🏍️", keywords: ["travel"] },
  { name: "bike", glyph: "🚲", keywords: ["travel", "cycling"] },
  { name: "map", glyph: "🗺️", keywords: ["travel", "location"] },
  { name: "compass", glyph: "🧭", keywords: ["direction", "travel"] },
  { name: "camping", glyph: "🏕️", keywords: ["outdoors"] },
  { name: "beach_umbrella", glyph: "🏖️", keywords: ["vacation", "beach"] },
  { name: "house", glyph: "🏠", keywords: ["home"] },
  { name: "office", glyph: "🏢", keywords: ["work", "building"] },
  { name: "hospital", glyph: "🏥", keywords: ["health"] },
  { name: "church", glyph: "⛪", keywords: ["building"] },
  { name: "bridge_at_night", glyph: "🌉", keywords: ["city"] },
  { name: "city_sunset", glyph: "🌆", keywords: ["city"] },

  // More smileys & people
  { name: "sunglasses", glyph: "😎", keywords: ["cool"] },
  { name: "sweat_smile", glyph: "😅", keywords: ["nervous", "phew"] },
  { name: "hugging_face", glyph: "🤗", keywords: ["hug"] },
  { name: "pleading_face", glyph: "🥺", keywords: ["please", "puppy eyes"] },
  { name: "smiling_face_with_3_hearts", glyph: "🥰", keywords: ["love", "adore"] },
  { name: "saluting_face", glyph: "🫡", keywords: ["salute", "yes sir"] },
  { name: "face_with_hand_over_mouth", glyph: "🤭", keywords: ["oops", "giggle"] },
  { name: "face_with_monocle", glyph: "🧐", keywords: ["inspect", "curious"] },
  { name: "nerd_face", glyph: "🤓", keywords: ["geek", "glasses"] },
  { name: "face_with_cowboy_hat", glyph: "🤠", keywords: ["yeehaw"] },
  { name: "disappointed", glyph: "😞", keywords: ["sad"] },
  { name: "confused", glyph: "😕", keywords: ["huh"] },
  { name: "weary", glyph: "😩", keywords: ["tired", "ugh"] },
  { name: "tired_face", glyph: "😫", keywords: ["exhausted"] },
  { name: "yawning_face", glyph: "🥱", keywords: ["bored", "sleepy"] },
  { name: "drooling_face", glyph: "🤤", keywords: ["yum"] },
  { name: "money_mouth_face", glyph: "🤑", keywords: ["rich", "money"] },
  { name: "face_with_thermometer", glyph: "🤒", keywords: ["sick", "ill"] },
  { name: "face_with_head_bandage", glyph: "🤕", keywords: ["hurt", "injured"] },
  { name: "sneezing_face", glyph: "🤧", keywords: ["sick", "achoo"] },
  { name: "woozy_face", glyph: "🥴", keywords: ["dizzy", "drunk"] },
  { name: "face_vomiting", glyph: "🤮", keywords: ["sick", "gross"] },
  { name: "lying_face", glyph: "🤥", keywords: ["liar", "pinocchio"] },
  { name: "kissing", glyph: "😗", keywords: ["kiss"] },
  { name: "kissing_smiling_eyes", glyph: "😙", keywords: ["kiss"] },
  { name: "kissing_closed_eyes", glyph: "😚", keywords: ["kiss"] },
  { name: "stuck_out_tongue_winking_eye", glyph: "😜", keywords: ["silly", "wink"] },
  { name: "stuck_out_tongue_closed_eyes", glyph: "😝", keywords: ["silly"] },
  { name: "hushed", glyph: "😯", keywords: ["surprised"] },
  { name: "open_mouth", glyph: "😮", keywords: ["wow", "surprised"] },
  { name: "astonished", glyph: "😲", keywords: ["shocked"] },
  { name: "white_frowning_face", glyph: "☹️", keywords: ["sad", "frown"] },
  { name: "disappointed_relieved", glyph: "😥", keywords: ["sad", "phew"] },
  { name: "smiling_imp", glyph: "😈", keywords: ["devil", "evil"] },
  { name: "imp", glyph: "👿", keywords: ["devil", "angry"] },
  { name: "jack_o_lantern", glyph: "🎃", keywords: ["halloween", "pumpkin"] },
  { name: "point_up", glyph: "☝️", keywords: ["one", "up"] },
  { name: "hand", glyph: "✋", keywords: ["stop", "high five"] },
  { name: "raised_back_of_hand", glyph: "🤚", keywords: ["stop"] },
  { name: "spock-hand", glyph: "🖖", keywords: ["vulcan", "live long"] },
  { name: "pinched_fingers", glyph: "🤌", keywords: ["italian", "chef"] },
  { name: "writing_hand", glyph: "✍️", keywords: ["write", "note"] },
  { name: "nail_care", glyph: "💅", keywords: ["nails", "sassy"] },
  { name: "selfie", glyph: "🤳", keywords: ["photo"] },
  { name: "eye", glyph: "👁️", keywords: ["look", "see"] },
  { name: "lips", glyph: "👄", keywords: ["mouth", "kiss"] },
  { name: "baby", glyph: "👶", keywords: ["child"] },
  { name: "man", glyph: "👨", keywords: ["person"] },
  { name: "woman", glyph: "👩", keywords: ["person"] },
  { name: "older_adult", glyph: "🧓", keywords: ["elderly"] },
  { name: "cop", glyph: "👮", keywords: ["police"] },
  { name: "dancer", glyph: "💃", keywords: ["dance", "party"] },
  { name: "man_dancing", glyph: "🕺", keywords: ["dance", "party"] },
  { name: "walking", glyph: "🚶", keywords: ["walk"] },
  { name: "couple", glyph: "👫", keywords: ["pair", "friends"] },
  { name: "family", glyph: "👪", keywords: ["parents", "kids"] },
  { name: "speech_balloon", glyph: "💬", keywords: ["chat", "comment"] },
  { name: "thought_balloon", glyph: "💭", keywords: ["think", "idea"] },
  { name: "zzz", glyph: "💤", keywords: ["sleep", "tired"] },
  { name: "anger", glyph: "💢", keywords: ["angry", "mad"] },
  { name: "dizzy", glyph: "💫", keywords: ["star", "sparkle"] },
  { name: "sweat_drops", glyph: "💦", keywords: ["water", "splash"] },
  { name: "dash", glyph: "💨", keywords: ["fast", "wind", "gone"] },
  { name: "bomb", glyph: "💣", keywords: ["explode"] },

  // Symbols & arrows
  { name: "heavy_plus_sign", glyph: "➕", keywords: ["add", "plus"] },
  { name: "heavy_minus_sign", glyph: "➖", keywords: ["minus", "remove"] },
  { name: "heavy_dollar_sign", glyph: "💲", keywords: ["money", "dollar"] },
  { name: "arrow_up", glyph: "⬆️", keywords: ["up"] },
  { name: "arrow_down", glyph: "⬇️", keywords: ["down"] },
  { name: "arrow_left", glyph: "⬅️", keywords: ["left", "back"] },
  { name: "arrow_right", glyph: "➡️", keywords: ["right", "next"] },
  { name: "arrows_counterclockwise", glyph: "🔄", keywords: ["refresh", "sync", "repeat"] },
  { name: "repeat", glyph: "🔁", keywords: ["loop", "again"] },
  { name: "fast_forward", glyph: "⏩", keywords: ["skip", "next"] },
  { name: "rewind", glyph: "⏪", keywords: ["back"] },
  { name: "arrow_forward", glyph: "▶️", keywords: ["play", "start"] },
  { name: "double_vertical_bar", glyph: "⏸️", keywords: ["pause"] },
  { name: "black_square_for_stop", glyph: "⏹️", keywords: ["stop"] },
  { name: "one", glyph: "1️⃣", keywords: ["number", "first"] },
  { name: "two", glyph: "2️⃣", keywords: ["number", "second"] },
  { name: "three", glyph: "3️⃣", keywords: ["number", "third"] },
  { name: "hash", glyph: "#️⃣", keywords: ["number", "channel"] },
  { name: "copyright", glyph: "©️", keywords: ["legal"] },
  { name: "tm", glyph: "™️", keywords: ["trademark"] },
  { name: "information_source", glyph: "ℹ️", keywords: ["info"] },
  { name: "sos", glyph: "🆘", keywords: ["help", "emergency"] },
  { name: "new", glyph: "🆕", keywords: ["fresh"] },
  { name: "free", glyph: "🆓", keywords: ["gratis"] },
  { name: "cool", glyph: "🆒", keywords: ["nice"] },
  { name: "ok", glyph: "🆗", keywords: ["okay", "fine"] },
  { name: "up", glyph: "🆙", keywords: ["level"] },
  { name: "vs", glyph: "🆚", keywords: ["versus"] },
  { name: "radio_button", glyph: "🔘", keywords: ["select"] },
  { name: "white_circle", glyph: "⚪", keywords: ["circle"] },
  { name: "black_circle", glyph: "⚫", keywords: ["circle"] },
  { name: "red_circle", glyph: "🔴", keywords: ["circle", "record", "live"] },
  { name: "large_blue_circle", glyph: "🔵", keywords: ["circle"] },
  { name: "large_green_circle", glyph: "🟢", keywords: ["circle", "online", "go"] },
  { name: "large_yellow_circle", glyph: "🟡", keywords: ["circle", "warning"] },
  { name: "large_orange_circle", glyph: "🟠", keywords: ["circle"] },
  { name: "large_purple_circle", glyph: "🟣", keywords: ["circle"] },
  { name: "white_large_square", glyph: "⬜", keywords: ["square"] },
  { name: "black_large_square", glyph: "⬛", keywords: ["square"] },
  { name: "large_red_square", glyph: "🟥", keywords: ["square"] },
  { name: "large_green_square", glyph: "🟩", keywords: ["square"] },
  { name: "large_blue_square", glyph: "🟦", keywords: ["square"] },
  { name: "small_red_triangle", glyph: "🔺", keywords: ["up", "triangle"] },
  { name: "small_red_triangle_down", glyph: "🔻", keywords: ["down", "triangle"] },
  { name: "diamond_shape_with_a_dot_inside", glyph: "💠", keywords: ["diamond"] },
  { name: "ballot_box_with_check", glyph: "☑️", keywords: ["check", "done", "tick"] },
  { name: "ballot_box_with_ballot", glyph: "🗳️", keywords: ["vote", "election"] },
  { name: "eight_spoked_asterisk", glyph: "✳️", keywords: ["asterisk", "star"] },
  { name: "infinity", glyph: "♾️", keywords: ["forever", "loop"] },
  { name: "peace_symbol", glyph: "☮️", keywords: ["peace"] },
  { name: "yin_yang", glyph: "☯️", keywords: ["balance"] },
  { name: "male_sign", glyph: "♂️", keywords: ["male"] },
  { name: "female_sign", glyph: "♀️", keywords: ["female"] },
  { name: "wheelchair", glyph: "♿", keywords: ["accessible"] },
  { name: "no_entry_sign", glyph: "🚫", keywords: ["forbidden", "banned", "no"] },
  { name: "no_smoking", glyph: "🚭", keywords: ["forbidden"] },
  { name: "underage", glyph: "🔞", keywords: ["adult", "nsfw"] },
  { name: "restroom", glyph: "🚻", keywords: ["toilet", "wc"] },
  { name: "atm", glyph: "🏧", keywords: ["cash", "bank"] },
  { name: "musical_score", glyph: "🎼", keywords: ["music"] },
  { name: "notes", glyph: "🎶", keywords: ["music", "song"] },
  { name: "crown", glyph: "👑", keywords: ["king", "queen", "royal"] },
  { name: "gem", glyph: "💎", keywords: ["diamond", "precious"] },
  { name: "ring", glyph: "💍", keywords: ["engaged", "married"] },
  { name: "key", glyph: "🔑", keywords: ["unlock", "password"] },
  { name: "hammer", glyph: "🔨", keywords: ["build", "fix"] },
  { name: "scissors", glyph: "✂️", keywords: ["cut"] },
  { name: "pencil2", glyph: "✏️", keywords: ["write", "edit"] },
  { name: "book", glyph: "📖", keywords: ["read", "docs"] },
  { name: "books", glyph: "📚", keywords: ["read", "library"] },
  { name: "newspaper", glyph: "📰", keywords: ["news"] },
  { name: "shopping_trolley", glyph: "🛒", keywords: ["cart", "buy"] },
  { name: "fireworks", glyph: "🎆", keywords: ["celebrate", "new year"] },
  { name: "christmas_tree", glyph: "🎄", keywords: ["holiday", "xmas"] },
  { name: "santa", glyph: "🎅", keywords: ["christmas"] },
  { name: "snowman", glyph: "⛄", keywords: ["winter"] },
  { name: "hourglass_flowing_sand", glyph: "⏳", keywords: ["waiting", "time"] },
  { name: "watch", glyph: "⌚", keywords: ["time"] },
  { name: "stopwatch", glyph: "⏱️", keywords: ["timer", "speed"] },
  { name: "syringe", glyph: "💉", keywords: ["vaccine", "medical"] },
  { name: "pill", glyph: "💊", keywords: ["medicine"] },
  { name: "stethoscope", glyph: "🩺", keywords: ["doctor", "health"] },
  { name: "toilet", glyph: "🚽", keywords: ["bathroom"] },
  { name: "shower", glyph: "🚿", keywords: ["bath"] },
  { name: "bed", glyph: "🛏️", keywords: ["sleep"] },
  { name: "door", glyph: "🚪", keywords: ["exit", "enter"] },
  { name: "flashlight", glyph: "🔦", keywords: ["torch", "light"] },
  { name: "candle", glyph: "🕯️", keywords: ["light"] },
  { name: "satellite_antenna", glyph: "📡", keywords: ["signal", "broadcast"] },
  { name: "telescope", glyph: "🔭", keywords: ["space", "look"] },
  { name: "microscope", glyph: "🔬", keywords: ["science", "lab"] },
  { name: "test_tube", glyph: "🧪", keywords: ["science", "experiment"] },
  { name: "dna", glyph: "🧬", keywords: ["science", "genetics"] },
  { name: "magnet", glyph: "🧲", keywords: ["attract"] },
  { name: "puzzle_piece", glyph: "🧩", keywords: ["puzzle", "fit"] },
  { name: "teddy_bear", glyph: "🧸", keywords: ["toy", "cute"] },
  { name: "pinata", glyph: "🪅", keywords: ["party", "pinata"] },
  { name: "ribbon", glyph: "🎀", keywords: ["ribbon", "bow"] },
  { name: "money_with_wings", glyph: "💸", keywords: ["money", "spend", "flying"] },
  { name: "coin", glyph: "🪙", keywords: ["money", "crypto"] },
  { name: "chart", glyph: "💹", keywords: ["stocks", "growth"] },
  { name: "bar_chart", glyph: "📊", keywords: ["stats", "graph"] },
  { name: "receipt", glyph: "🧾", keywords: ["invoice", "bill"] },
  { name: "briefcase", glyph: "💼", keywords: ["work", "business"] },
  { name: "card_index_dividers", glyph: "🗂️", keywords: ["files", "organise"] },
  { name: "wastebasket", glyph: "🗑️", keywords: ["trash", "delete", "bin"] },
  { name: "label", glyph: "🏷️", keywords: ["tag", "price"] },
  { name: "date", glyph: "📆", keywords: ["calendar", "schedule"] },
  { name: "spiral_calendar_pad", glyph: "🗓️", keywords: ["calendar", "schedule"] },
  { name: "world_map", glyph: "🗺️", keywords: ["map", "travel"] },
  { name: "rotating_light", glyph: "🚨", keywords: ["alert", "emergency", "siren"] },
  { name: "construction", glyph: "🚧", keywords: ["wip", "work in progress", "blocked"] },
  { name: "traffic_light", glyph: "🚦", keywords: ["stop", "go"] },
  { name: "fuelpump", glyph: "⛽", keywords: ["gas", "petrol"] },
  { name: "flying_saucer", glyph: "🛸", keywords: ["ufo", "alien"] },
  { name: "helicopter", glyph: "🚁", keywords: ["fly"] },
  { name: "sailboat", glyph: "⛵", keywords: ["boat", "sail"] },
  { name: "tent", glyph: "⛺", keywords: ["camping"] },
  { name: "statue_of_liberty", glyph: "🗽", keywords: ["new york", "usa"] },
  { name: "tokyo_tower", glyph: "🗼", keywords: ["japan", "tokyo"] },
  { name: "moyai", glyph: "🗿", keywords: ["stone", "easter island"] },
  { name: "second_place_medal", glyph: "🥈", keywords: ["silver", "second"] },
  { name: "third_place_medal", glyph: "🥉", keywords: ["bronze", "third"] },
  { name: "sports_medal", glyph: "🏅", keywords: ["award", "win"] },
  { name: "cricket_bat_and_ball", glyph: "🏏", keywords: ["cricket", "sports"] },
  { name: "badminton_racquet_and_shuttlecock", glyph: "🏸", keywords: ["badminton", "sports"] },
  { name: "table_tennis_paddle_and_ball", glyph: "🏓", keywords: ["ping pong", "sports"] },
  { name: "boxing_glove", glyph: "🥊", keywords: ["boxing", "fight"] },
  { name: "martial_arts_uniform", glyph: "🥋", keywords: ["karate", "judo"] },
  { name: "skier", glyph: "⛷️", keywords: ["ski", "snow"] },
  { name: "surfer", glyph: "🏄", keywords: ["surf", "beach"] },
  { name: "mountain_bicyclist", glyph: "🚵", keywords: ["cycling", "mountain"] },
  { name: "horse_racing", glyph: "🏇", keywords: ["horse", "race"] },
  { name: "person_in_lotus_position", glyph: "🧘", keywords: ["yoga", "meditate", "calm"] },
  { name: "climbing", glyph: "🧗", keywords: ["climb", "rock"] },

  // Flags
  { name: "checkered_flag", glyph: "🏁", keywords: ["race", "finish"] },
  { name: "rainbow-flag", glyph: "🏳️‍🌈", keywords: ["pride", "lgbt"] },
  { name: "waving_white_flag", glyph: "🏳️", keywords: ["surrender", "peace"] },
  { name: "waving_black_flag", glyph: "🏴", keywords: ["pirate"] },
  { name: "pirate_flag", glyph: "🏴‍☠️", keywords: ["pirate", "skull"] },
  { name: "flag-us", glyph: "🇺🇸", keywords: ["usa", "america", "united states"] },
  { name: "flag-gb", glyph: "🇬🇧", keywords: ["uk", "britain", "england", "united kingdom"] },
  { name: "flag-in", glyph: "🇮🇳", keywords: ["india"] },
  { name: "flag-ca", glyph: "🇨🇦", keywords: ["canada"] },
  { name: "flag-au", glyph: "🇦🇺", keywords: ["australia"] },
  { name: "flag-eu", glyph: "🇪🇺", keywords: ["europe", "european union"] },
  { name: "flag-de", glyph: "🇩🇪", keywords: ["germany", "deutschland"] },
  { name: "flag-fr", glyph: "🇫🇷", keywords: ["france"] },
  { name: "flag-es", glyph: "🇪🇸", keywords: ["spain"] },
  { name: "flag-it", glyph: "🇮🇹", keywords: ["italy"] },
  { name: "flag-pt", glyph: "🇵🇹", keywords: ["portugal"] },
  { name: "flag-nl", glyph: "🇳🇱", keywords: ["netherlands", "holland"] },
  { name: "flag-be", glyph: "🇧🇪", keywords: ["belgium"] },
  { name: "flag-ch", glyph: "🇨🇭", keywords: ["switzerland"] },
  { name: "flag-at", glyph: "🇦🇹", keywords: ["austria"] },
  { name: "flag-ie", glyph: "🇮🇪", keywords: ["ireland"] },
  { name: "flag-se", glyph: "🇸🇪", keywords: ["sweden"] },
  { name: "flag-no", glyph: "🇳🇴", keywords: ["norway"] },
  { name: "flag-dk", glyph: "🇩🇰", keywords: ["denmark"] },
  { name: "flag-fi", glyph: "🇫🇮", keywords: ["finland"] },
  { name: "flag-pl", glyph: "🇵🇱", keywords: ["poland"] },
  { name: "flag-cz", glyph: "🇨🇿", keywords: ["czech", "czechia"] },
  { name: "flag-gr", glyph: "🇬🇷", keywords: ["greece"] },
  { name: "flag-tr", glyph: "🇹🇷", keywords: ["turkey", "türkiye"] },
  { name: "flag-ua", glyph: "🇺🇦", keywords: ["ukraine"] },
  { name: "flag-ru", glyph: "🇷🇺", keywords: ["russia"] },
  { name: "flag-jp", glyph: "🇯🇵", keywords: ["japan"] },
  { name: "flag-kr", glyph: "🇰🇷", keywords: ["korea", "south korea"] },
  { name: "flag-cn", glyph: "🇨🇳", keywords: ["china"] },
  { name: "flag-hk", glyph: "🇭🇰", keywords: ["hong kong"] },
  { name: "flag-tw", glyph: "🇹🇼", keywords: ["taiwan"] },
  { name: "flag-sg", glyph: "🇸🇬", keywords: ["singapore"] },
  { name: "flag-my", glyph: "🇲🇾", keywords: ["malaysia"] },
  { name: "flag-th", glyph: "🇹🇭", keywords: ["thailand"] },
  { name: "flag-vn", glyph: "🇻🇳", keywords: ["vietnam"] },
  { name: "flag-id", glyph: "🇮🇩", keywords: ["indonesia"] },
  { name: "flag-ph", glyph: "🇵🇭", keywords: ["philippines"] },
  { name: "flag-pk", glyph: "🇵🇰", keywords: ["pakistan"] },
  { name: "flag-bd", glyph: "🇧🇩", keywords: ["bangladesh"] },
  { name: "flag-lk", glyph: "🇱🇰", keywords: ["sri lanka"] },
  { name: "flag-np", glyph: "🇳🇵", keywords: ["nepal"] },
  { name: "flag-ae", glyph: "🇦🇪", keywords: ["uae", "dubai", "emirates"] },
  { name: "flag-sa", glyph: "🇸🇦", keywords: ["saudi arabia"] },
  { name: "flag-il", glyph: "🇮🇱", keywords: ["israel"] },
  { name: "flag-eg", glyph: "🇪🇬", keywords: ["egypt"] },
  { name: "flag-za", glyph: "🇿🇦", keywords: ["south africa"] },
  { name: "flag-ng", glyph: "🇳🇬", keywords: ["nigeria"] },
  { name: "flag-ke", glyph: "🇰🇪", keywords: ["kenya"] },
  { name: "flag-br", glyph: "🇧🇷", keywords: ["brazil"] },
  { name: "flag-ar", glyph: "🇦🇷", keywords: ["argentina"] },
  { name: "flag-mx", glyph: "🇲🇽", keywords: ["mexico"] },
  { name: "flag-co", glyph: "🇨🇴", keywords: ["colombia"] },
  { name: "flag-cl", glyph: "🇨🇱", keywords: ["chile"] },
  { name: "flag-nz", glyph: "🇳🇿", keywords: ["new zealand"] },
  { name: "flag-un", glyph: "🇺🇳", keywords: ["united nations"] },
];

const EMOJI_BY_NAME = new Map(EMOJI_LIST.map((e) => [e.name, e]));

export function emojiGlyph(name: string): string {
  return EMOJI_BY_NAME.get(name)?.glyph ?? `:${name}:`;
}

/** The glyph for a standard shortcode, or null when it isn't in the curated set (e.g. a custom workspace emoji). */
export function lookupEmojiGlyph(name: string): string | null {
  return EMOJI_BY_NAME.get(name)?.glyph ?? null;
}

export function searchEmoji(query: string, limit = 60): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  // No query: show the whole curated set (the picker's grid scrolls) rather than an arbitrary
  // early slice — slicing here previously meant only the first category (Smileys) was ever
  // reachable without typing a search term.
  if (!q) return EMOJI_LIST;

  const results: EmojiEntry[] = [];
  for (const entry of EMOJI_LIST) {
    if (entry.name.includes(q) || entry.keywords.some((k) => k.includes(q))) {
      results.push(entry);
      if (results.length >= limit) break;
    }
  }
  return results;
}
